// Human-readable names for the fields that appear in validation messages and toasts.
export const FIELD_LABELS: Record<string, string> = {
  // Employee
  permanentId: "Employee Code",
  dynamicId: "Organisation Code",
  teamOfficeCode: "Team Office Code",
  name: "Name",
  phone: "Mobile number",
  email: "Email",
  personalEmail: "Personal email",
  fatherName: "Father name",
  gender: "Gender",
  dateOfBirth: "Date of birth",
  pan: "PAN number",
  aadhaar: "Aadhaar number",
  address1: "Address line 1",
  address2: "Address line 2",
  pinCode: "PIN code",
  state: "State / UT",
  bankHolderName: "Bank holder name",
  bankName: "Bank name",
  accountNumber: "Account number",
  ifscCode: "IFSC code",
  pfAccountNumber: "PF account number",
  uanNumber: "UAN number",
  esicNumber: "ESIC number",
  numberOfOutlets: "No. of outlets",
  companyId: "Company",
  locationId: "Location",
  cityId: "City",
  branchId: "Branch",
  outletModelId: "Outlet model",
  specialBranchCodeId: "Special / area code",
  departmentId: "Department",
  employeeRoleId: "Employee role",
  designationId: "Designation",
  costCentreId: "Cost centre",
  status: "Status",
  joiningDate: "Date of joining",
  exitDate: "Last day of working",
  // Asset
  faId: "Asset ID",
  category: "Asset category",
  description: "Asset description",
  makeModel: "Make / model",
  serialNo: "Serial no.",
  vendorName: "Vendor name",
  invoiceNo: "Invoice no.",
  invoiceDate: "Invoice date",
  capitalisationDate: "Capitalisation date",
  poGrnNo: "PO / GRN no.",
  purchaseCost: "Purchase cost",
  freight: "Freight",
  installationCost: "Installation / erection",
  otherCost: "Other direct cost",
  gstAmount: "GST amount",
  itcEligible: "ITC eligible",
  itcAvailed: "ITC availed",
  depreciationMethod: "Depreciation method",
  usefulLife: "Useful life (years)",
  residualValue: "Residual value",
  taxBlock: "Income-tax block",
  taxRate: "Tax depreciation rate",
  disposalDate: "Disposal date",
  disposalReason: "Disposal reason",
  disposalRemarks: "Disposal remarks",
  saleProceeds: "Sale proceeds",
  verificationDate: "Verification date",
  verificationStatus: "Verification status",
  // Transfers / requests
  assetId: "Asset",
  receiverEmployeeCode: "Receiving Employee ID",
  reason: "Reason",
  effectiveDate: "Effective date",
  registeredDate: "Registered date",
  // Masters
  code: "Code",
  // Auth
  password: "Password",
  currentPassword: "Current password",
  newPassword: "New password",
  confirmPassword: "Confirm new password",
  otp: "One-time password (OTP)",
};

export function fieldLabel(field: string): string {
  const known = FIELD_LABELS[field];
  if (known) return known;
  const spaced = field.replace(/([a-z0-9])([A-Z])/g, "$1 $2").toLowerCase();
  return spaced.charAt(0).toUpperCase() + spaced.slice(1);
}
