import * as XLSX from "xlsx";
import { PrismaClient, Gender } from "@prisma/client";
import { dynamicEmployeeCode } from "../src/lib/ids";
const db = new PrismaClient();
const text = (v: unknown) => String(v ?? "").trim();
const phone = (v: unknown) => text(v).replace(/\D/g, "").slice(-10);
const asDate = (v: unknown) => v instanceof Date ? v : v ? new Date(v as string | number) : null;
const yes = (v: unknown) => /^(yes|y|true)$/i.test(text(v));
const headers = (r: unknown[]) => Object.fromEntries(r.map((v, i) => [text(v).toLowerCase(), i]));
const get = (row: unknown[], map: Record<string, number>, ...names: string[]) => { for (const name of names) { const value = row[map[name.toLowerCase()]]; if (value !== undefined && text(value)) return value; } return undefined; };
const raw = (head: unknown[], row: unknown[]) => Object.fromEntries(head.map((h, i) => [text(h), row[i] instanceof Date ? (row[i] as Date).toISOString() : row[i]]));
async function master(kind: "location" | "city" | "branch" | "outletModel" | "department" | "employeeRole" | "designation", name: unknown, code?: unknown) { const value = text(name); if (!value) return null; const normalized = (text(code) || value).replace(/[^A-Za-z0-9-]/g, "-").toUpperCase().slice(0, 20); const delegate = db[kind] as unknown as { upsert: (args: unknown) => Promise<{ id: string; code: string }> }; return delegate.upsert({ where: { name: value }, update: { code: normalized }, create: { name: value, code: normalized } }); }
async function salaryMasters(path: string) { const b = XLSX.readFile(path, { cellDates: true }); const rows = XLSX.utils.sheet_to_json<unknown[]>(b.Sheets["Color and codes Scheme"], { header: 1, defval: "" });
  for (const r of rows.slice(9, 14)) { await master("city", r[0], r[0]); const special = text(r[2]); if (special) await db.specialBranchCode.upsert({ where: { name: special }, update: { code: special }, create: { name: special, code: special } }); }
  for (const r of rows.slice(16, 36)) { await master("designation", r[2], r[3]); await master("designation", r[6], r[7]); }
  for (const r of rows.slice(36, 43)) await master("branch", r[2], r[3]);
  for (const r of rows.slice(41, 56)) await master("department", r[6], r[7]);
}
async function employees(path: string) { const b = XLSX.readFile(path, { cellDates: true }); const candidates = ["Mater data of Empoloyee (2)", "Mater data of Empoloyee", "Master data From April Employee", "Backup"]; let sheet: unknown[][] = []; for (const name of candidates) { const ws = b.Sheets[name]; if (!ws) continue; const values = XLSX.utils.sheet_to_json<unknown[]>(ws, { header: 1, defval: "" }); if (values.length > sheet.length) sheet = values; }
  const head = sheet[0] ?? [], map = headers(head); let imported = 0, skipped = 0;
  for (const row of sheet.slice(1)) { const permanentId = text(get(row, map, "Employee Code")); const name = text(get(row, map, "Name as per Pan Card", "Emlpoyee Name")); const mobile = phone(get(row, map, "Mobile Number", "Mobile")); if (!/^EMP\d{4,}$/.test(permanentId) || !name || mobile.length !== 10) { skipped++; continue; }
    const location = await master("location", get(row, map, "Work Place - Location", "Work Location ")); const city = await master("city", get(row, map, "City"), get(row, map, "City Code")); const outletModel = await master("outletModel", get(row, map, "Outlet Model"), get(row, map, "Outlet Model Code")); const department = await master("department", get(row, map, "Department"), get(row, map, "Department Code")); const employeeRole = await master("employeeRole", get(row, map, "Employee Role"), get(row, map, "Employee Role Code")); const designation = await master("designation", get(row, map, "Designation")); const genderText = text(get(row, map, "Gender")).toUpperCase(); const gender: Gender | undefined = genderText.startsWith("F") ? "FEMALE" : genderText.startsWith("M") ? "MALE" : undefined; const numberOfOutlets = Number(get(row, map, "No Of Outlets", "No. of Outlets") || 0) || null;
    const specialName = get(row, map, "Special Code", "Area Code", "Special / Area Code"); const specialCode = text(specialName); const special = specialCode ? await db.specialBranchCode.upsert({ where: { code: specialCode }, update: {}, create: { name: specialCode, code: specialCode } }) : null;
    const dynamicId = dynamicEmployeeCode({ cityCode: city?.code, outletModelCode: outletModel?.code, specialCode: special?.code, numberOfOutlets, departmentCode: department?.code, employeeRoleCode: employeeRole?.code, employeeCode: permanentId });
    const payload = { teamOfficeCode: text(get(row, map, "Team office code", "Team office number")) || null, name, phone: `+91${mobile}`, email: text(get(row, map, "Work Email")) || null, personalEmail: text(get(row, map, "Personal Email")) || null, fatherName: text(get(row, map, "Father Name")) || null, gender, dateOfBirth: asDate(get(row, map, "Date of Birth")), pan: text(get(row, map, "PAN Number")) || null, aadhaar: text(get(row, map, "Aadhar Card Number"))?.replace(/\s/g, "") || null, address1: text(get(row, map, "Personal AddressLine1")) || null, address2: text(get(row, map, "Personal AddressLine2")) || null, pinCode: text(get(row, map, "Pin code")) || null, state: text(get(row, map, "State")) || null, bankHolderName: text(get(row, map, "Bank Holder Name")) || null, bankName: text(get(row, map, "Bank Name")) || null, accountNumber: text(get(row, map, "Account Number")) || null, ifscCode: text(get(row, map, "IFSC Code")) || null, pfEligible: yes(get(row, map, "Is Eligible For PF", "Opted for PF")), pfAccountNumber: text(get(row, map, "PF Account Number")) || null, uanNumber: text(get(row, map, "UAN Number", "UAN")) || null, esicNumber: text(get(row, map, "ESIC Number")) || null, joiningDate: asDate(get(row, map, "Date of Joining", "Joining Date")), exitDate: asDate(get(row, map, "Last day of Working", "Last Working Day")), locationId: location?.id, cityId: city?.id, outletModelId: outletModel?.id, specialBranchCodeId: special?.id, numberOfOutlets, departmentId: department?.id, employeeRoleId: employeeRole?.id, designationId: designation?.id, dynamicId };
    const employee = await db.employee.upsert({ where: { permanentId }, update: payload, create: { permanentId, ...payload } }); await db.employeeHistory.create({ data: { employeeId: employee.id, snapshot: raw(head, row) as never, reason: "Legacy workbook import" } }); imported++;
  } return { imported, skipped, mappedColumns: head.length };
}
async function main() { const masterPath = process.env.SOURCE_MASTER_XLSX, salaryPath = process.env.SOURCE_SALARY_XLSX; if (!masterPath || !salaryPath) throw new Error("Set SOURCE_MASTER_XLSX and SOURCE_SALARY_XLSX to the supplied workbook paths."); await salaryMasters(salaryPath); console.log(await employees(masterPath)); await db.$executeRaw`SELECT setval('employee_code_seq', GREATEST((SELECT COALESCE(MAX(SUBSTRING("permanentId" FROM '[0-9]+$')::BIGINT), 0) FROM "Employee"), 1))`; }
main().finally(() => db.$disconnect());
